language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: XWm9hyjrt291DuGV+J1kgTLlgIzPrxnCYeV7FeahGuMwAvYXRIUtL3FDTYD2wNpGJDceit4fWlX/TZ3pwuDuqhJH72d5OhCXfdxXRy3EfnHv2mEYLz4QyVYj7d07K4g1tTDz1iUZ5ImEVHyWXlDaIwQMnWx87IWGJey2hRn1x+FUH8gEk8RjXJV2EkgNw/Sgek3sU2uJYrXLIH+yKMtc22RCxtqgXdF/xQJlqnBDM075ams9SEG5Cj4A6cyfHFiFxWKWynEdQmJmVx3aGlsMQUp7YYRNbU6+B5Tn3UJeVLbRlPoaLLx8dRQVNvlBjzbkFaIuXAg5tTcZAib6h7BS/Luhr3bKXxdynrhj+dQ0P5zfCIqnCoZ6A3zXnIklmK0W9Kj5AmbfeKNr6TQdjVoPFpp7qV9HtcNBEX/SP1jogI34V62sCQtWhJVSetOyGebB1Kc8BF4pSesJ0oMXoQxiqfQ2UTyKTfrpZfkpoHgxDKFfd21mxPLADJkqeSGbhfkVIki86DFStMfS0jj6ONF6a3xRmMnmNjUF3ZbUfY6a+6K2FZgLfr1lNPt7sE9a03vnfFiwYhwLVEUd4P0ll+yMKzscfxAfeJFN4CM0pf7XVlqjNaVKRyrMG/Pz2QzriUPX+s3ZpBEQYrBOGVfZFu6mFh8Xt92SsJNMa0Y9UQ9x/wk=
  file: build/libs/*.jar
  file_glob: true
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-remedy-plugin
notifications:
  slack:
    secure: hu129Fieb6ihC7LfbPk9NR1kee9bSKVX9HB1tGk6CEEUhqGeHsX6xWKIznDVzkae5EGN8wwJH9Wb8djuiTbYtQBKl06+3IoMZt2wqZJbFcoBdP5lwQlefakYSurDuqYxBWsc5eER9tNjhPqjSuRaDYvlflB0LxTnK7LBCbeHuTua3pOBHbuOgFJqUcXpvpdYliQJQZ2Sjm/5C5inxYU78BvmDxVf44q/l8v+8fdYFNLnQRPRDs2YjwW7F4TqvW11bIT3Kxuf7K2goa6g5eJH9qHoMYDw1Av43AhcibyriAMsqD4Lud3XlI4Ed0RN2UOjdj9utSvlRbnGfMs9sdRy+Rq0lGCOUOPBimyZnZMhpQBjhZwh0T0EcDctmjqtB+Sg3q8pqPJe3pTQYOFEK4A0IcPpwhxXet32g8yaaMeHpsG9XyVSKK8FTeWNsPjxr7VfOD5dRyBdaK6VlNpTVQ/9CkZIHe2FrUhv1FVJ2Oy+OAXMAmWzJDeagjuFRyC+QCL8mXJVc4ELjLHHhmOq8u2gos5LqVEGfkzoaRKWGCJrmXVAhF3ZhBHACwmahryM0h6q3A54+hx1ZutBpIcV3ck73kB/DTBsMCin6zWNyEyowRQPHeDcmXuMwUEGVyzbg5sE18QlNRSiOXX9yaCd+A2iaKyOx3nRI3dq+Lo/vGQpzGQ=
